version: "3.1"
services:
  localhost:
    container_name: localhost
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 8galXOCluTBZFyr66cFQsF56IzsNd4CG
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres

volumes:
  postgres:
