version: "3.5"
services:
  postgres:
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres:
